### ISSUE TITLE
Pro Display XDR support

### ISSUE THREAD

**Issue by cor** [nikosdion/asdcontrol#1]
This is a really cool tool! Does it work with Pro Display XDR, and if not, is there another tool that does?

**Comment by nikosdion** [comment]
Thank you!

To be honest, I've no idea if Pro Display XDR would work with this. I do not have one. Where I live, it costs just over $6000 for the cheapest option, and I can't justify the expense as I'm a software developer, not a graphics or video artist :)

**Comment by supermarin** [comment]
I've just tested this on a Pro display XDR and it works!

If you're open we can document it properly and double check if the values are right (5960 increments, max brightness)

**Comment by nikosdion** [comment]
@supermarin The steps and max brightness in Apple Studio Display are different than Pro Display XDR. 

If you can do a PR to do the checks only when it's a Pro Display XDR I'll be happy to merge it. As I said, I can't do that because I can't test it. The hardware price is absurd in my country 😅

**Comment by supermarin** [comment]
Just checked, looks like max brightness I can set is indeed 60000, like implemented in #2 .
The only missing part is the documentation.

Also - I haven't tested with an actual nit meter to see what this corresponds to in real life. It does get very bright at value 60000, so I imagine the corresponding nits are different between XDR and Studio display.

**Comment by supermarin** [comment]
Hmm sorry I realized after typing this - the 60000 is limited by the implementation.
If I catch time I'll recompile with a different value and see what happens.
I imagine there needs to be a HID documentation somewhere for these values, any chance you have a link for the Studio Display?

**Comment by nikosdion** [comment]
I have not actually found any documentation to speak of. Everything you see there was just a silly amount of trial and error.

I don't have a nit meter here either, but I am positive the values for Studio Display and Pro Display XDR will result in different nits. The top brightness is very different for each one of them.

**Comment by supermarin** [comment]
Makes sense. I'm imagining that XDR would [peak at 500 nits SDR](https://support.apple.com/kb/SP800?locale=en_US) since Linux doesn't have support for HDR, unless this is somehow brute forcing overly bright content. What I'm trying to achieve with all of this is avoid damaging the screen in any way (i.e force it to sustain 1000+ nits) and hurting the eyes too

**Comment by nikosdion** [comment]
From experience, anything over 500 nits looks **plenty** bright at the 0.6m – 0.8m distance we usually have to our screens. Even on a bright, summer day in Athens, Greece when my Apple Watch thinks I am basking in the sun (when I'm actually still inside my office!) the 600 nits were a tad too bright to me — and I am facing the window, mind you. I am pretty sure once you are close to that level you'll just know to stop.
